# Imports

In [2]:
import numpy as np
import tensorflow as tf

# Constants

In [3]:
X_TEST_PATH = 'MNIST/load_xtest.csv'
Y_TEST_PATH = 'MNIST/load_ytest.csv'

# Load the Data

In [4]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)
print(f'Shape of y_test {y_test.shape}')

Shape of y_test (10000,)


In [5]:
x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=float)
print(f'Shape of x_test {x_test.shape}')

Shape of x_test (10000, 784)


In [6]:
x_test[0]

array([0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
      

In [19]:
y_test[0]

7

In [20]:
np.savetxt(fname='xtest0_ylabel7', X=[x_test[0]], delimiter=',', fmt='%1.2f')

# Load the Model

In [7]:
model = tf.saved_model.load(r'C:\Users\srini\MLProjects\my_saved_model')

In [8]:
input_signature = model.signatures[list(model.signatures.keys())[0]].structured_input_signature
print(input_signature)

((), {'inputs': TensorSpec(shape=(None, 784), dtype=tf.float32, name='inputs')})


In [9]:
input_tensor_name = input_signature[1]['inputs'].name
print(input_tensor_name)

inputs


In [10]:
infer = model.signatures["serving_default"]
input_tensor_name = infer.structured_input_signature[1]['inputs'].name

# Check Results

In [11]:
predictions = infer(tf.constant(x_test, dtype=tf.float32, name=input_tensor_name))

In [12]:
print(predictions)

{'output_0': <tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[2.5575405e-02, 2.3908927e-03, 5.8542252e-01, ..., 9.9996799e-01,
        1.3608750e-03, 1.7027548e-01],
       [8.2984626e-01, 9.7629839e-01, 9.9999988e-01, ..., 3.2039800e-06,
        9.5180345e-01, 4.0462924e-06],
       [1.4708702e-03, 9.9926019e-01, 6.1776644e-01, ..., 4.6556023e-01,
        1.3611072e-01, 1.0050070e-03],
       ...,
       [1.7005691e-06, 2.3567147e-06, 3.9612558e-05, ..., 4.7015485e-01,
        5.6523108e-01, 3.8981792e-01],
       [7.9688136e-05, 1.6798015e-04, 9.7110773e-05, ..., 1.7604189e-02,
        8.6097437e-01, 6.3795887e-06],
       [7.5033709e-02, 1.2363013e-04, 2.7415201e-02, ..., 3.8948015e-06,
        1.0277981e-02, 4.9976178e-04]], dtype=float32)>}


In [13]:
print(predictions['output_0'].numpy())

[[2.5575405e-02 2.3908927e-03 5.8542252e-01 ... 9.9996799e-01
  1.3608750e-03 1.7027548e-01]
 [8.2984626e-01 9.7629839e-01 9.9999988e-01 ... 3.2039800e-06
  9.5180345e-01 4.0462924e-06]
 [1.4708702e-03 9.9926019e-01 6.1776644e-01 ... 4.6556023e-01
  1.3611072e-01 1.0050070e-03]
 ...
 [1.7005691e-06 2.3567147e-06 3.9612558e-05 ... 4.7015485e-01
  5.6523108e-01 3.8981792e-01]
 [7.9688136e-05 1.6798015e-04 9.7110773e-05 ... 1.7604189e-02
  8.6097437e-01 6.3795887e-06]
 [7.5033709e-02 1.2363013e-04 2.7415201e-02 ... 3.8948015e-06
  1.0277981e-02 4.9976178e-04]]


In [14]:
predicted_labels = tf.argmax(predictions['output_0'], axis=1).numpy()
#print(predicted_labels)
predicted_labels[0:5]

array([7, 2, 1, 0, 4], dtype=int64)

# Comparision

In [15]:
y_test[0:5]

array([7, 2, 1, 0, 4])

In [16]:
# The values of predicted_labels and the actual values from y_test macth for the first 5 inputs.
#It means the thing is working fine.

In [17]:
no_correct = sum(np.equal(predicted_labels, y_test))
accuracy = no_correct/len(predicted_labels)

In [18]:
print(f'The accuracy of the model used is:{accuracy*100}%')

The accuracy of the model used is:97.37%
